apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonebookapp-frontend-deployment
  namespace: phonebookapp-final-proj
  labels:
    app: phonebookapp
specs:
  replicas: 2
  selector:
    matchLabels:
      app: phonebookapp
      tier: frontend
  template:
    metadata:
      name: phonebookapp-frontend-pod
      namespace: phonebookapp-final-proj
      labels:
        app: phonebookapp
        tier: frontend
    specs:
      containers:
        - name: phonebookapp-frontend
          image: {registry_name}/{image}:{version}
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_BACKEND_URL
              valueFrom:
                secretKeyRef:
                  name: phonebookapp-secrets
                  key: REACT_APP_BACKEND_URL