apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonebookapp-frontend-deployment
  namespace: phonebookapp-final-proj
  labels:
    app: phonebookapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phonebookapp
      tier: frontend
  template:
    metadata:
      name: phonebookapp-frontend-pod
      namespace: phonebookapp-final-proj
      labels:
        app: phonebookapp
        tier: frontend
    spec:
      containers:
        - name: phonebookapp-frontend
          image: img_name_placeholder
          ports:
            - containerPort: 80