apiVersion: v1
kind: Deployment
metadata:
  name: phonebookapp-db-deployment
  namespace: phonebookapp-final-proj
  labels:
    app: phonebookapp
specs:
  replicas: 1
  selector:
    matchLabels:
      app: phonebookapp
      tier: db
  template:
    metadata:
      name: phonebookapp-db-pod
      namespace: phonebookapp-final-proj
      labels:
        app: phonebookapp
        tier: db
    specs:
      containers:
        - name: phonebookapp-db
          image: {registry_name}/{image}:{version}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: phonebookapp-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: phonebookapp-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: phonebookapp-secrets
                  key: POSTGRES_DB


