apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonebookapp-db-deployment
  namespace: phonebookapp-final-proj
  labels:
    app: phonebookapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phonebookapp
      tier: db
  template:
    metadata:
      name: phonebookapp-db-pod
      namespace: phonebookapp-final-proj
      labels:
        app: phonebookapp
        tier: db
    spec:
      containers:
        - name: phonebookapp-db
          image: img_name_placeholder
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: phonebookapp-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: phonebookapp-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: phonebookapp-secrets
                  key: POSTGRES_DB
            - name: RUNNING_NEV
              value: "DB"
            - name: DB_SERVICE_IP
              value: [db-service-ip]
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "python3 init_database.py"]
