apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonebookapp-backend-deployment
  namespace: phonebookapp-final-proj
  labels:
    app: phonebookapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phonebookapp
      tier: backend
  template:
    metadata:
      name: phonebookapp-backend-pod
      namespace: phonebookapp-final-proj
      labels:
        app: phonebookapp
        tier: backend
    spec:
      containers:
        - name: phonebookapp-backend
          image: img_name_placeholder
          ports:
            - containerPort: 80
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                    name: phonebookapp-secrets
                    key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: phonebookapp-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: phonebookapp-secrets
                  key: POSTGRES_DB
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: phonebookapp-secrets
                  key: PG_HOST
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: phonebookapp-secrets
                  key: JWT_SECRET_KEY

