apiVersion: v1
kind: Deployment
metadata:
  name: phonebookapp-backend-deployment
  namespace: phonebookapp-final-proj
  labels:
    app: phonebookapp
specs:
  replicas: 2
  selector:
    matchLabels:
      app: phonebookapp
      tier: backend
  template:
    metadata:
      name: phonebookapp-backend-pod
      namespace: phonebookapp-final-proj
      labels:
        app: phonebookapp
        tier: backend
    specs:
      containers:
        - name: phonebookapp-backend
          image: {registry_name}/{image}:{version}
          ports:
            - containerPort: 80
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  - name: phonebookapp-secrets
                    key: DB_URL
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  - name: phonebookapp-secrets
                    key: JWT_SECRET_KEY

