apiVersion: v1
kind: Secrets
metadata:
  name: phonebookapp-secrets
  namespace: phonebookapp-final-proj
data:
  POSTGRES_USER: [pg_user]
  POSTGRES_PASSWORD: [pg_password]
  POSTGRES_DB: [pg_db]
  DB_URL: [db_url]
  JWT_SECRET_KEY: [jwt_secret_key]
  REACT_APP_API_URL: [react_app_api_url]
