apiVersion: v1
kind: Secrets
metadata:
  name: phonebookapp-secrets
  namespace: phonebookapp-final-proj
data:
  POSTGRES_USER: [pg_user]
  POSTGRES_PASSWORD: [pg_password]
  POSTGRES_DB: [pg_db]
  DB_SERVICE_NAME: [db_service_name]
  JWT_SECRET_KEY: [jwt_secret_key]