apiVersion: v1
kind: Service
metadata:
  name: phonebookapp-backend-service
  namespace: phonebookapp-final-proj
  labels:
    app: phonebookapp
specs:
  selector:
    app: phonebookapp
    tier: backend
  type: ClusterIp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80