apiVersion: v1
kind: Service
metadata:
  namespace: phonebookapp-final-proj
  name: phonebookapp-db-service
  labels:
    app: phonebookapp
spec:
  selector:
    app: phonebook
    tier: db
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
