apiVersion: v1
kind: Service
metadata:
  name: phonebookapp-frontend-service
  namespace: phonebookapp-final-proj
  labels:
    app: phonebookapp
specs:
  selector:
    app: phonebookapp
    tier: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001